volume_mute:
  description: Mute a cast volume tracker's volume.
  fields:
    entity_id:
      description: Name(s) of entities to mute.
      example: 'cast_volume_tracker.kitchen_speakers'
    is_volume_muted:
      description: True/false for mute/unmute.
      example: true

volume_set:
  description: Set a cast volume tracker's volume level.
  fields:
    entity_id:
      description: Name(s) of entities to set volume level on.
      example: 'cast_volume_tracker.kitchen_speakers'
    volume_level:
      description: Volume level to set as float.
      example: 0.6

volume_up:
  description: Turn a cast volume tracker up.
  fields:
    entity_id:
      description: Name(s) of entities to turn volume up on.
      example: 'cast_volume_tracker.kitchen_speakers'

volume_down:
  description: Turn a cast volume tracker down.
  fields:
    entity_id:
      description: Name(s) of entities to turn volume down on.
      example: 'cast_volume_tracker.kitchen_speakers'

enable_volume_management:
  description: Enable or disable volume management.
  fields:
    is_volume_management_enabled:
      description: True/false for enable/disable.
      example: true
